// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(WGDBContext))]
    [Migration("20240924123719_addBaseTables")]
    partial class addBaseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.models.Field", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListOfValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInHUD")
                        .HasColumnType("boolean");

                    b.Property<bool>("SystemCol")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Field", (string)null);
                });

            modelBuilder.Entity("Server.models.GisObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Heading")
                        .HasColumnType("double precision");

                    b.Property<Guid>("IdentityNo")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ObjectType_id")
                        .HasColumnType("bigint");

                    b.Property<long>("Parent_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObjectType_id");

                    b.HasIndex("parent_id");

                    b.ToTable("GisObject", (string)null);
                });

            modelBuilder.Entity("Server.models.GisObjectMetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<long>("Field_id")
                        .HasColumnType("bigint");

                    b.Property<long>("Object_id")
                        .HasColumnType("bigint");

                    b.Property<long>("gisObjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("gisObjectId");

                    b.ToTable("GisObjectMetaData", (string)null);
                });

            modelBuilder.Entity("Server.models.LocalizationString", b =>
                {
                    b.Property<decimal>("StrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("StrKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StrValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StrId");

                    b.ToTable("LocalizationString", (string)null);
                });

            modelBuilder.Entity("Server.models.ObjectType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Pic")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("ObjectType", (string)null);
                });

            modelBuilder.Entity("Server.models.ObjectTypeMetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Field_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ObjectType_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Field_Id");

                    b.HasIndex("ObjectType_Id");

                    b.ToTable("ObjectTypeMetaData", (string)null);
                });

            modelBuilder.Entity("Server.models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Server.models.GisObject", b =>
                {
                    b.HasOne("Server.models.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectType_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.models.GisObject", "Parent")
                        .WithMany()
                        .HasForeignKey("parent_id");

                    b.Navigation("ObjectType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Server.models.GisObjectMetaData", b =>
                {
                    b.HasOne("Server.models.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.models.GisObject", "gisObject")
                        .WithMany()
                        .HasForeignKey("gisObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("gisObject");
                });

            modelBuilder.Entity("Server.models.ObjectTypeMetaData", b =>
                {
                    b.HasOne("Server.models.Field", "Field")
                        .WithMany()
                        .HasForeignKey("Field_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.models.ObjectType", "TypeOfObject")
                        .WithMany()
                        .HasForeignKey("ObjectType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("TypeOfObject");
                });
#pragma warning restore 612, 618
        }
    }
}
